development:
  adapter: postgresql
  encoding: unicode
  database: store_development10
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: store_test10
  pool: 5
  username:
  password:
